fix: fix storybook

diff --git a/.github/workflows/docs-storybook.yml b/.github/workflows/docs-storybook.yml
--- a/.github/workflows/docs-storybook.yml
+++ b/.github/workflows/docs-storybook.yml
@@ -1,70 +1,84 @@
-name: Build and Deploy
+name: Build and Deploy Storybook
 on:
   push:
-    paths: [
-        'src/client/stories/**',
-        'src/client/components/**',
-        'src/client/pages/**',
-      ] # Trigger the action only when files change in the folders defined here
+    branches: 
+      - main
+    paths: 
+      - 'src/client/stories/**'
+      - 'src/client/components/**'
+      - 'src/client/pages/**'
+    
 
-  workflow_dispatch: # Allow manual triggering of the workflow
-  
-  jobs:
-    build-and-deploy:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout🛎️
-          uses: actions/checkout@v2.3.1
-          with:
-            persist-credentials: false
-        - name: Detect package manager
-          id: detect-package-manager
-          run: |
-            if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-              echo "manager=yarn" >> $GITHUB_OUTPUT
-              echo "command=install" >> $GITHUB_OUTPUT
-              echo "runner=yarn" >> $GITHUB_OUTPUT
-              exit 0
-            elif [ -f "${{ github.workspace }}/package.json" ]; then
-              echo "manager=npm" >> $GITHUB_OUTPUT
-              echo "command=ci" >> $GITHUB_OUTPUT
-              echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-              exit 0
-            else
-              echo "Unable to determine packager manager"
-              exit 1
-            fi
-        - name: Setup Node
-          uses: actions/setup-node@v3
-          with:
-            node-version: '16'
-            cache: ${{ steps.detect-package-manager.outputs.manager }}
-        # - name: Setup Pages
-        # uses: actions/configure-pages@v2
-        # with:
-        # Automatically inject basePath in your Next.js configuration file and disable
-        # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
-        # You may remove this line if you want to manage the configuration yourself.
-        #  static_site_generator: next
-        - name: Restore cache
-          uses: actions/cache@v3
-          with:
-            path: |
-              .next/cache
-            # Generate a new cache whenever packages or source files change.
-            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
-            # If source files changed but packages didn't, rebuild from a prior cache.
-            restore-keys: |
-              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
-        - name: Install dependencies🔧
-          run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-        - name: Build with Next.js🔧
-          run: ${{ steps.detect-package-manager.outputs.runner }}  next build
-        - name: Deploy 🚀
-          uses: JamesIves/github-pages-deploy-action@3.6.2
-          with:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-            BRANCH: main # The branch the action should deploy to.
-            FOLDER: docs # The folder that the build-storybook script generates files.
-            CLEAN: true # Automatically remove deleted files from the deploy branch
-            TARGET_FOLDER: docs # The folder that we serve our Storybook files from
+  # Allow manual triggering of the workflow
+  workflow_dispatch:
+
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+# Allow one concurrent deployment
+concurrency:
+  group: 'pages'
+  cancel-in-progress: true
+
+jobs:
+  build-and-deploy:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout🛎️
+        uses: actions/checkout@v2.3.1
+        with:
+          persist-credentials: false
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      # - name: Setup Pages
+      # uses: actions/configure-pages@v2
+      # with:
+      # Automatically inject basePath in your Next.js configuration file and disable
+      # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
+      # You may remove this line if you want to manage the configuration yourself.
+      #  static_site_generator: next
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+      - name: Install dependencies🔧
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Next.js🔧
+        run: ${{ steps.detect-package-manager.outputs.runner }}  next build
+      - name: Deploy 🚀
+        uses: JamesIves/github-pages-deploy-action@3.6.2
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BRANCH: main # The branch the action should deploy to.
+          FOLDER: docs # The folder that the build-storybook script generates files.
+          CLEAN: true # Automatically remove deleted files from the deploy branch
+          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
